/********************************************************************
* Embedreco_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error Embedreco_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableEmbedreco_Dict();
extern void G__cpp_setup_inheritanceEmbedreco_Dict();
extern void G__cpp_setup_typetableEmbedreco_Dict();
extern void G__cpp_setup_memvarEmbedreco_Dict();
extern void G__cpp_setup_globalEmbedreco_Dict();
extern void G__cpp_setup_memfuncEmbedreco_Dict();
extern void G__cpp_setup_funcEmbedreco_Dict();
extern void G__set_cpp_environmentEmbedreco_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "BbcEmbedreco.h"
#include "DchEmbedreco.h"
#include "PadEmbedreco.h"
#include "TecEmbedreco.h"
#include "TofEmbedreco.h"
#include "TofwEmbedreco.h"
#include "CrkEmbedreco.h"
#include "EmcEmbedreco.h"
#include "AccEmbedreco.h"
#include "MixEmbedreco.h"
#include "EvaEmbedreco.h"
#include "EmbedVertexSelect.h"
#include "SvxEmbedSimhit.h"
#include "SvxEmbedEval.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__Embedreco_DictLN_string;
extern G__linked_taginfo G__Embedreco_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__Embedreco_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Embedreco_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__Embedreco_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Embedreco_DictLN_Fun4AllBase;
extern G__linked_taginfo G__Embedreco_DictLN_PHCompositeNode;
extern G__linked_taginfo G__Embedreco_DictLN_SubsysReco;
extern G__linked_taginfo G__Embedreco_DictLN_VtxMixer;
extern G__linked_taginfo G__Embedreco_DictLN_BbcEmbedreco;
extern G__linked_taginfo G__Embedreco_DictLN_dDchTracksWrapper;
extern G__linked_taginfo G__Embedreco_DictLN_dDchTracksExtWrapper;
extern G__linked_taginfo G__Embedreco_DictLN_mNewDchInitializer;
extern G__linked_taginfo G__Embedreco_DictLN_mNewDchCandidatory;
extern G__linked_taginfo G__Embedreco_DictLN_DchMixer;
extern G__linked_taginfo G__Embedreco_DictLN_DchEmbedreco;
extern G__linked_taginfo G__Embedreco_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__Embedreco_DictLN_TFile;
extern G__linked_taginfo G__Embedreco_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__Embedreco_DictLN_TNtuple;
extern G__linked_taginfo G__Embedreco_DictLN_padInclBad;
extern G__linked_taginfo G__Embedreco_DictLN_padDetectorGeo;
extern G__linked_taginfo G__Embedreco_DictLN_padEvtToRaw;
extern G__linked_taginfo G__Embedreco_DictLN_PadRecModule;
extern G__linked_taginfo G__Embedreco_DictLN_PadMixer;
extern G__linked_taginfo G__Embedreco_DictLN_PadEmbedreco;
extern G__linked_taginfo G__Embedreco_DictLN_mTecHoughTrackModule;
extern G__linked_taginfo G__Embedreco_DictLN_TecAddressObject;
extern G__linked_taginfo G__Embedreco_DictLN_TecGeometryObject;
extern G__linked_taginfo G__Embedreco_DictLN_TecCalibrationObject;
extern G__linked_taginfo G__Embedreco_DictLN_TecMixer;
extern G__linked_taginfo G__Embedreco_DictLN_TecEmbedreco;
extern G__linked_taginfo G__Embedreco_DictLN_TofAddressObject;
extern G__linked_taginfo G__Embedreco_DictLN_TofCalibObject;
extern G__linked_taginfo G__Embedreco_DictLN_TofGeometryObject;
extern G__linked_taginfo G__Embedreco_DictLN_TofMixer;
extern G__linked_taginfo G__Embedreco_DictLN_TofEmbedreco;
extern G__linked_taginfo G__Embedreco_DictLN_TofwMixer;
extern G__linked_taginfo G__Embedreco_DictLN_TofwGeometry;
extern G__linked_taginfo G__Embedreco_DictLN_TofwEmbedreco;
extern G__linked_taginfo G__Embedreco_DictLN_CrkMixer;
extern G__linked_taginfo G__Embedreco_DictLN_CrkEmbedreco;
extern G__linked_taginfo G__Embedreco_DictLN_mEmcClusterizerv0;
extern G__linked_taginfo G__Embedreco_DictLN_EmcMixer;
extern G__linked_taginfo G__Embedreco_DictLN_EmcEmbedreco;
extern G__linked_taginfo G__Embedreco_DictLN_AccEvent;
extern G__linked_taginfo G__Embedreco_DictLN_AccGeometry;
extern G__linked_taginfo G__Embedreco_DictLN_AccHit;
extern G__linked_taginfo G__Embedreco_DictLN_AccRaw;
extern G__linked_taginfo G__Embedreco_DictLN_AccEmbedreco;
extern G__linked_taginfo G__Embedreco_DictLN_MixEmbedreco;
extern G__linked_taginfo G__Embedreco_DictLN_PHEmbedMCEvaluator;
extern G__linked_taginfo G__Embedreco_DictLN_PHEmbededEvent;
extern G__linked_taginfo G__Embedreco_DictLN_EvaEmbedreco;
extern G__linked_taginfo G__Embedreco_DictLN_EmbedVertexSelect;
extern G__linked_taginfo G__Embedreco_DictLN_TRandom3;
extern G__linked_taginfo G__Embedreco_DictLN_svxDetectorGeo;
extern G__linked_taginfo G__Embedreco_DictLN_SvxEmbedSimhit;
extern G__linked_taginfo G__Embedreco_DictLN_SvxCentralTrack;
extern G__linked_taginfo G__Embedreco_DictLN_SvxClusterList;
extern G__linked_taginfo G__Embedreco_DictLN_SvxEmbedEval;

/* STUB derived class for protected member access */
