//
// File generated by rootcint at Thu Mar 12 15:15:35 2026

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME embedana_Dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "embedana_Dict.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
      #if !(defined(R__ACCESS_IN_SYMBOL) || defined(R__USE_SHADOW_CLASS))
      typedef ::embedana embedana;
      #else
      class embedana  :  public ::SubsysReco {
         public:
         //friend XX;
         // To force the creation of a virtual table, throw just in case.
         virtual ~embedana() throw() {};
         int EventNumber; //
         int InPartNumber; //
         int InIDread; //
         string m_outFileName; //
         int fill_TTree; //
         int remove_cluster_hits; //
         string local_filepath; //
         string local_oscarpath; //
         vector< double > vertexes; //
         ::InData InData_read[100000]; //
         int dcmap_runs[9][500]; //
         float dcmap_xx1[9][2][2][20]; //
         float dcmap_yy1[9][2][2][20]; //
         float dcmap_xx2[9][2][2][20]; //
         float dcmap_yy2[9][2][2][20]; //
         float dcmap_xx3[9][2][2][20]; //
         float dcmap_yy3[9][2][2][20]; //
         float dcmap_xx4[9][2][2][20]; //
         float dcmap_yy4[9][2][2][20]; //
         int TRIGGERBIT; //
         float BBC_VERTEX_CUT; //
         int QUALITY[3]; //
         float Z_GLOBAL; //<|cut value|
         int DC_DEADMAP; //0--w/o dc dead map, 1--w/ dc dead map
         float E_PT; //
         float MAX_PT; //
         float N0; //>cut value
         float DISP; //<cut value
         float CHI2_NPE0; //< cut value
         float EOVERP; //
         float DEP[2]; //
         float PROB; //>cut value
         float TEMC; //
         float EMCDPHI; //
         float EMCDZ; //
         float EMCSDPHI; //
         float EMCSDZ; //
         float RICH_GHOST; //RICH ghost cut
         ::DileptonAnalysis::MyEventContainer* event_container; //
      };
      #endif

   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace DileptonAnalysis {
   namespace ROOTDict {
      inline ::ROOT::TGenericClassInfo *GenerateInitInstance();
      static void DileptonAnalysis_Dictionary();

      // Function generating the singleton type initializer
      inline ::ROOT::TGenericClassInfo *GenerateInitInstance()
      {
         static ::ROOT::TGenericClassInfo 
            instance("DileptonAnalysis", 0 /*version*/, "./MyEvent.h", 36,
                     ::ROOT::DefineBehavior((void*)0,(void*)0),
                     &DileptonAnalysis_Dictionary, 0);
         return &instance;
      }
      // Insure that the inline function is _not_ optimized away by the compiler
      ::ROOT::TGenericClassInfo *(*_R__UNIQUE_(InitFunctionKeeper))() = &GenerateInitInstance;  
      // Static variable to force the class initialization
      static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstance(); R__UseDummy(_R__UNIQUE_(Init));

      // Dictionary for non-ClassDef classes
      static void DileptonAnalysis_Dictionary() {
         GenerateInitInstance()->GetClass();
      }

   }
}

namespace ROOTDict {
   void embedana_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void embedana_Dictionary();
   static void *new_embedana(void *p = 0);
   static void *newArray_embedana(Long_t size, void *p);
   static void delete_embedana(void *p);
   static void deleteArray_embedana(void *p);
   static void destruct_embedana(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::embedana*)
   {
      // Make sure the shadow class has the right sizeof
      R__ASSERT(sizeof(::embedana) == sizeof( ::ROOTShadow::Shadow::embedana));
      ::embedana *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::embedana),0);
      static ::ROOT::TGenericClassInfo 
         instance("embedana", "./embedana.h", 85,
                  typeid(::embedana), ::ROOT::DefineBehavior(ptr, ptr),
                  &embedana_ShowMembers, &embedana_Dictionary, isa_proxy, 4,
                  sizeof(::embedana) );
      instance.SetNew(&new_embedana);
      instance.SetNewArray(&newArray_embedana);
      instance.SetDelete(&delete_embedana);
      instance.SetDeleteArray(&deleteArray_embedana);
      instance.SetDestructor(&destruct_embedana);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::embedana*)
   {
      return GenerateInitInstanceLocal((::embedana*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::embedana*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void embedana_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::embedana*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

//______________________________________________________________________________
namespace ROOTDict {
   void embedana_ShowMembers(void *obj, TMemberInspector &R__insp)
   {
      // Inspect the data members of an object of class embedana.
      typedef ::ROOTShadow::Shadow::embedana ShadowClass;
      ShadowClass *sobj = (ShadowClass*)obj;
      if (sobj) { } // Dummy usage just in case there is no datamember.

      TClass *R__cl  = ::ROOTDict::GenerateInitInstanceLocal((const ::embedana*)0x0)->GetClass();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "EventNumber", &sobj->EventNumber);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "InPartNumber", &sobj->InPartNumber);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "InIDread", &sobj->InIDread);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_outFileName", (void*)&sobj->m_outFileName);
      R__insp.InspectMember("string", (void*)&sobj->m_outFileName, "m_outFileName.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fill_TTree", &sobj->fill_TTree);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "remove_cluster_hits", &sobj->remove_cluster_hits);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "local_filepath", (void*)&sobj->local_filepath);
      R__insp.InspectMember("string", (void*)&sobj->local_filepath, "local_filepath.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "local_oscarpath", (void*)&sobj->local_oscarpath);
      R__insp.InspectMember("string", (void*)&sobj->local_oscarpath, "local_oscarpath.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "vertexes", (void*)&sobj->vertexes);
      R__insp.InspectMember("vector<double>", (void*)&sobj->vertexes, "vertexes.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "InData_read[100000]", sobj->InData_read);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dcmap_runs[9][500]", sobj->dcmap_runs);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dcmap_xx1[9][2][2][20]", sobj->dcmap_xx1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dcmap_yy1[9][2][2][20]", sobj->dcmap_yy1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dcmap_xx2[9][2][2][20]", sobj->dcmap_xx2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dcmap_yy2[9][2][2][20]", sobj->dcmap_yy2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dcmap_xx3[9][2][2][20]", sobj->dcmap_xx3);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dcmap_yy3[9][2][2][20]", sobj->dcmap_yy3);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dcmap_xx4[9][2][2][20]", sobj->dcmap_xx4);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dcmap_yy4[9][2][2][20]", sobj->dcmap_yy4);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TRIGGERBIT", &sobj->TRIGGERBIT);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "BBC_VERTEX_CUT", &sobj->BBC_VERTEX_CUT);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "QUALITY[3]", sobj->QUALITY);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Z_GLOBAL", &sobj->Z_GLOBAL);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "DC_DEADMAP", &sobj->DC_DEADMAP);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "E_PT", &sobj->E_PT);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "MAX_PT", &sobj->MAX_PT);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "N0", &sobj->N0);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "DISP", &sobj->DISP);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "CHI2_NPE0", &sobj->CHI2_NPE0);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "EOVERP", &sobj->EOVERP);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "DEP[2]", sobj->DEP);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "PROB", &sobj->PROB);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TEMC", &sobj->TEMC);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "EMCDPHI", &sobj->EMCDPHI);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "EMCDZ", &sobj->EMCDZ);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "EMCSDPHI", &sobj->EMCSDPHI);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "EMCSDZ", &sobj->EMCSDZ);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "RICH_GHOST", &sobj->RICH_GHOST);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*event_container", &sobj->event_container);
      R__insp.GenericShowMembers("SubsysReco", ( ::SubsysReco * )( (::embedana*) obj ), false);
   }

}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_embedana(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::embedana : new ::embedana;
   }
   static void *newArray_embedana(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::embedana[nElements] : new ::embedana[nElements];
   }
   // Wrapper around operator delete
   static void delete_embedana(void *p) {
      delete ((::embedana*)p);
   }
   static void deleteArray_embedana(void *p) {
      delete [] ((::embedana*)p);
   }
   static void destruct_embedana(void *p) {
      typedef ::embedana current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::embedana

namespace ROOTDict {
   void vectorlEdoublegR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEdoublegR_Dictionary();
   static void *new_vectorlEdoublegR(void *p = 0);
   static void *newArray_vectorlEdoublegR(Long_t size, void *p);
   static void delete_vectorlEdoublegR(void *p);
   static void deleteArray_vectorlEdoublegR(void *p);
   static void destruct_vectorlEdoublegR(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const vector<double>*)
   {
      vector<double> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<double>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<double>", -2, "vector.dll", 0,
                  typeid(vector<double>), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &vectorlEdoublegR_Dictionary, isa_proxy, 0,
                  sizeof(vector<double>) );
      instance.SetNew(&new_vectorlEdoublegR);
      instance.SetNewArray(&newArray_vectorlEdoublegR);
      instance.SetDelete(&delete_vectorlEdoublegR);
      instance.SetDeleteArray(&deleteArray_vectorlEdoublegR);
      instance.SetDestructor(&destruct_vectorlEdoublegR);
      instance.AdoptCollectionProxyInfo( ::ROOT::TCollectionProxyInfo::Generate( ::ROOT::TCollectionProxyInfo::Pushback< vector<double> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<double>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEdoublegR_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const vector<double>*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_vectorlEdoublegR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<double> : new vector<double>;
   }
   static void *newArray_vectorlEdoublegR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<double>[nElements] : new vector<double>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEdoublegR(void *p) {
      delete ((vector<double>*)p);
   }
   static void deleteArray_vectorlEdoublegR(void *p) {
      delete [] ((vector<double>*)p);
   }
   static void destruct_vectorlEdoublegR(void *p) {
      typedef vector<double> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class vector<double>

/********************************************************
* embedana_Dict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableembedana_Dict();

extern "C" void G__set_cpp_environmentembedana_Dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("embedana.h");
  G__add_compiledheader("Run14AuAuLeptonCombyConstants.h");
  G__cpp_reset_tagtableembedana_Dict();
}
#include <new>
extern "C" int G__cpp_dllrevembedana_Dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* DileptonAnalysis */

/* embedana */
static int G__embedana_Dict_933_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   embedana* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 4:
     //m: 4
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new embedana(
*((string*) G__int(libp->para[0])), *((string*) G__int(libp->para[1]))
, *((string*) G__int(libp->para[2])), (const int) G__int(libp->para[3]));
     } else {
       p = new((void*) gvp) embedana(
*((string*) G__int(libp->para[0])), *((string*) G__int(libp->para[1]))
, *((string*) G__int(libp->para[2])), (const int) G__int(libp->para[3]));
     }
     break;
   case 3:
     //m: 3
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new embedana(
*((string*) G__int(libp->para[0])), *((string*) G__int(libp->para[1]))
, *((string*) G__int(libp->para[2])));
     } else {
       p = new((void*) gvp) embedana(
*((string*) G__int(libp->para[0])), *((string*) G__int(libp->para[1]))
, *((string*) G__int(libp->para[2])));
     }
     break;
   case 2:
     //m: 2
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new embedana(*((string*) G__int(libp->para[0])), *((string*) G__int(libp->para[1])));
     } else {
       p = new((void*) gvp) embedana(*((string*) G__int(libp->para[0])), *((string*) G__int(libp->para[1])));
     }
     break;
   case 1:
     //m: 1
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new embedana(*((string*) G__int(libp->para[0])));
     } else {
       p = new((void*) gvp) embedana(*((string*) G__int(libp->para[0])));
     }
     break;
   case 0:
     int n = G__getaryconstruct();
     if (n) {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new embedana[n];
       } else {
         p = new((void*) gvp) embedana[n];
       }
     } else {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new embedana;
       } else {
         p = new((void*) gvp) embedana;
       }
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__embedana_DictLN_embedana));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__embedana_Dict_933_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((const embedana*) G__getstructoffset())->Print((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__embedana_Dict_933_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   embedana* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new embedana(*(embedana*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__embedana_DictLN_embedana));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef embedana G__Tembedana;
static int G__embedana_Dict_933_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (embedana*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((embedana*) (soff+(sizeof(embedana)*i)))->~G__Tembedana();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (embedana*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((embedana*) (soff))->~G__Tembedana();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__embedana_Dict_933_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   embedana* dest = (embedana*) G__getstructoffset();
   *dest = *(embedana*) libp->para[0].ref;
   const embedana& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* DileptonAnalysis */

/* embedana */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncembedana_Dict {
 public:
  G__Sizep2memfuncembedana_Dict(): p(&G__Sizep2memfuncembedana_Dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncembedana_Dict::*p)();
};

size_t G__get_sizep2memfuncembedana_Dict()
{
  G__Sizep2memfuncembedana_Dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceembedana_Dict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__embedana_DictLN_embedana))) {
     embedana *G__Lderived;
     G__Lderived=(embedana*)0x1000;
     {
       SubsysReco *G__Lpbase=(SubsysReco*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__embedana_DictLN_embedana),G__get_linked_tagnum(&G__embedana_DictLN_SubsysReco),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       Fun4AllBase *G__Lpbase=(Fun4AllBase*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__embedana_DictLN_embedana),G__get_linked_tagnum(&G__embedana_DictLN_Fun4AllBase),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableembedana_Dict() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__embedana_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__embedana_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__embedana_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__embedana_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__embedana_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__embedana_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__embedana_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__embedana_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__embedana_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__embedana_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TBranch*>",117,G__get_linked_tagnum(&G__embedana_DictLN_maplEstringcOTBranchmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTBranchmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TBranch*>",117,G__get_linked_tagnum(&G__embedana_DictLN_maplEstringcOTBranchmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTBranchmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TBranch*>",117,G__get_linked_tagnum(&G__embedana_DictLN_maplEstringcOTBranchmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTBranchmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TBranch*,less<string> >",117,G__get_linked_tagnum(&G__embedana_DictLN_maplEstringcOTBranchmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTBranchmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,PHBoolean>",117,G__get_linked_tagnum(&G__embedana_DictLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,PHBoolean>",117,G__get_linked_tagnum(&G__embedana_DictLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<const std::string,TNamed*>",117,G__get_linked_tagnum(&G__embedana_DictLN_maplEconstsPstringcOTNamedmUcOlesslEconstsPstringgRcOallocatorlEpairlEconstsPstringcOTNamedmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<const string,TNamed*>",117,G__get_linked_tagnum(&G__embedana_DictLN_maplEconstsPstringcOTNamedmUcOlesslEconstsPstringgRcOallocatorlEpairlEconstsPstringcOTNamedmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<const string,TNamed*,less<const string> >",117,G__get_linked_tagnum(&G__embedana_DictLN_maplEconstsPstringcOTNamedmUcOlesslEconstsPstringgRcOallocatorlEpairlEconstsPstringcOTNamedmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::string>",117,G__get_linked_tagnum(&G__embedana_DictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__embedana_DictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__embedana_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__embedana_DictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__embedana_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__embedana_DictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__embedana_DictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<SubsysReco*,PHCompositeNode*> >",117,G__get_linked_tagnum(&G__embedana_DictLN_vectorlEpairlESubsysRecomUcOPHCompositeNodemUgRcOallocatorlEpairlESubsysRecomUcOPHCompositeNodemUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<SubsysReco*,PHCompositeNode*> >",117,G__get_linked_tagnum(&G__embedana_DictLN_vectorlEpairlESubsysRecomUcOPHCompositeNodemUgRcOallocatorlEpairlESubsysRecomUcOPHCompositeNodemUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__embedana_DictLN_reverse_iteratorlEvectorlEpairlESubsysRecomUcOPHCompositeNodemUgRcOallocatorlEpairlESubsysRecomUcOPHCompositeNodemUgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__embedana_DictLN_vectorlEpairlESubsysRecomUcOPHCompositeNodemUgRcOallocatorlEpairlESubsysRecomUcOPHCompositeNodemUgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__embedana_DictLN_reverse_iteratorlEvectorlEpairlESubsysRecomUcOPHCompositeNodemUgRcOallocatorlEpairlESubsysRecomUcOPHCompositeNodemUgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__embedana_DictLN_vectorlEpairlESubsysRecomUcOPHCompositeNodemUgRcOallocatorlEpairlESubsysRecomUcOPHCompositeNodemUgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<SubsysReco*,PHCompositeNode*> >",117,G__get_linked_tagnum(&G__embedana_DictLN_vectorlEpairlESubsysRecomUcOPHCompositeNodemUgRcOallocatorlEpairlESubsysRecomUcOPHCompositeNodemUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__embedana_DictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__embedana_DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__embedana_DictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__embedana_DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__embedana_DictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Fun4AllOutputManager*>",117,G__get_linked_tagnum(&G__embedana_DictLN_vectorlEFun4AllOutputManagermUcOallocatorlEFun4AllOutputManagermUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__embedana_DictLN_reverse_iteratorlEvectorlEFun4AllOutputManagermUcOallocatorlEFun4AllOutputManagermUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__embedana_DictLN_vectorlEFun4AllOutputManagermUcOallocatorlEFun4AllOutputManagermUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__embedana_DictLN_reverse_iteratorlEvectorlEFun4AllOutputManagermUcOallocatorlEFun4AllOutputManagermUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__embedana_DictLN_vectorlEFun4AllOutputManagermUcOallocatorlEFun4AllOutputManagermUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TDirectory*>",117,G__get_linked_tagnum(&G__embedana_DictLN_vectorlETDirectorymUcOallocatorlETDirectorymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__embedana_DictLN_reverse_iteratorlEvectorlETDirectorymUcOallocatorlETDirectorymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__embedana_DictLN_vectorlETDirectorymUcOallocatorlETDirectorymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__embedana_DictLN_reverse_iteratorlEvectorlETDirectorymUcOallocatorlETDirectorymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__embedana_DictLN_vectorlETDirectorymUcOallocatorlETDirectorymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Fun4AllHistoManager*>",117,G__get_linked_tagnum(&G__embedana_DictLN_vectorlEFun4AllHistoManagermUcOallocatorlEFun4AllHistoManagermUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__embedana_DictLN_reverse_iteratorlEvectorlEFun4AllHistoManagermUcOallocatorlEFun4AllHistoManagermUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__embedana_DictLN_vectorlEFun4AllHistoManagermUcOallocatorlEFun4AllHistoManagermUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__embedana_DictLN_reverse_iteratorlEvectorlEFun4AllHistoManagermUcOallocatorlEFun4AllHistoManagermUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__embedana_DictLN_vectorlEFun4AllHistoManagermUcOallocatorlEFun4AllHistoManagermUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,PHCompositeNode*>",117,G__get_linked_tagnum(&G__embedana_DictLN_maplEstringcOPHCompositeNodemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOPHCompositeNodemUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,PHCompositeNode*>",117,G__get_linked_tagnum(&G__embedana_DictLN_maplEstringcOPHCompositeNodemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOPHCompositeNodemUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,PHCompositeNode*>",117,G__get_linked_tagnum(&G__embedana_DictLN_maplEstringcOPHCompositeNodemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOPHCompositeNodemUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,PHCompositeNode*,less<string> >",117,G__get_linked_tagnum(&G__embedana_DictLN_maplEstringcOPHCompositeNodemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOPHCompositeNodemUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Fun4AllSyncManager*>",117,G__get_linked_tagnum(&G__embedana_DictLN_vectorlEFun4AllSyncManagermUcOallocatorlEFun4AllSyncManagermUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__embedana_DictLN_reverse_iteratorlEvectorlEFun4AllSyncManagermUcOallocatorlEFun4AllSyncManagermUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__embedana_DictLN_vectorlEFun4AllSyncManagermUcOallocatorlEFun4AllSyncManagermUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__embedana_DictLN_reverse_iteratorlEvectorlEFun4AllSyncManagermUcOallocatorlEFun4AllSyncManagermUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__embedana_DictLN_vectorlEFun4AllSyncManagermUcOallocatorlEFun4AllSyncManagermUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,int>",117,G__get_linked_tagnum(&G__embedana_DictLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,int>",117,G__get_linked_tagnum(&G__embedana_DictLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,float>",117,G__get_linked_tagnum(&G__embedana_DictLN_maplEstringcOfloatcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOfloatgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,float>",117,G__get_linked_tagnum(&G__embedana_DictLN_maplEstringcOfloatcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOfloatgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,double>",117,G__get_linked_tagnum(&G__embedana_DictLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,double>",117,G__get_linked_tagnum(&G__embedana_DictLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,std::string>",117,G__get_linked_tagnum(&G__embedana_DictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,std::string>",117,G__get_linked_tagnum(&G__embedana_DictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,string>",117,G__get_linked_tagnum(&G__embedana_DictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,string,less<string> >",117,G__get_linked_tagnum(&G__embedana_DictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("set<unsigned int>",117,G__get_linked_tagnum(&G__embedana_DictLN_setlEunsignedsPintcOlesslEunsignedsPintgRcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("set<unsigned int,less<unsigned int> >",117,G__get_linked_tagnum(&G__embedana_DictLN_setlEunsignedsPintcOlesslEunsignedsPintgRcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__embedana_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__embedana_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__embedana_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__embedana_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__embedana_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__embedana_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__embedana_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__embedana_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__embedana_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__embedana_DictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__embedana_DictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__embedana_DictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__embedana_DictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__embedana_DictLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__embedana_DictLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__embedana_DictLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__embedana_DictLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__embedana_DictLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__embedana_DictLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__embedana_DictLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__embedana_DictLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__embedana_DictLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__embedana_DictLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__embedana_DictLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__embedana_DictLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__embedana_DictLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__embedana_DictLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__embedana_DictLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__embedana_DictLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__embedana_DictLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,float>",117,G__get_linked_tagnum(&G__embedana_DictLN_maplEintcOfloatcOlesslEintgRcOallocatorlEpairlEconstsPintcOfloatgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,float,less<int> >",117,G__get_linked_tagnum(&G__embedana_DictLN_maplEintcOfloatcOlesslEintgRcOallocatorlEpairlEconstsPintcOfloatgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<DileptonAnalysis::MyBDTHit>",117,G__get_linked_tagnum(&G__embedana_DictLN_vectorlEDileptonAnalysiscLcLMyBDTHitcOallocatorlEDileptonAnalysiscLcLMyBDTHitgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__embedana_DictLN_reverse_iteratorlEvectorlEDileptonAnalysiscLcLMyBDTHitcOallocatorlEDileptonAnalysiscLcLMyBDTHitgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__embedana_DictLN_vectorlEDileptonAnalysiscLcLMyBDTHitcOallocatorlEDileptonAnalysiscLcLMyBDTHitgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__embedana_DictLN_reverse_iteratorlEvectorlEDileptonAnalysiscLcLMyBDTHitcOallocatorlEDileptonAnalysiscLcLMyBDTHitgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__embedana_DictLN_vectorlEDileptonAnalysiscLcLMyBDTHitcOallocatorlEDileptonAnalysiscLcLMyBDTHitgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<DileptonAnalysis::MyElectron>",117,G__get_linked_tagnum(&G__embedana_DictLN_vectorlEDileptonAnalysiscLcLMyElectroncOallocatorlEDileptonAnalysiscLcLMyElectrongRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__embedana_DictLN_reverse_iteratorlEvectorlEDileptonAnalysiscLcLMyElectroncOallocatorlEDileptonAnalysiscLcLMyElectrongRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__embedana_DictLN_vectorlEDileptonAnalysiscLcLMyElectroncOallocatorlEDileptonAnalysiscLcLMyElectrongRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__embedana_DictLN_reverse_iteratorlEvectorlEDileptonAnalysiscLcLMyElectroncOallocatorlEDileptonAnalysiscLcLMyElectrongRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__embedana_DictLN_vectorlEDileptonAnalysiscLcLMyElectroncOallocatorlEDileptonAnalysiscLcLMyElectrongRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<DileptonAnalysis::MyCluster>",117,G__get_linked_tagnum(&G__embedana_DictLN_vectorlEDileptonAnalysiscLcLMyClustercOallocatorlEDileptonAnalysiscLcLMyClustergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__embedana_DictLN_reverse_iteratorlEvectorlEDileptonAnalysiscLcLMyClustercOallocatorlEDileptonAnalysiscLcLMyClustergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__embedana_DictLN_vectorlEDileptonAnalysiscLcLMyClustercOallocatorlEDileptonAnalysiscLcLMyClustergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__embedana_DictLN_reverse_iteratorlEvectorlEDileptonAnalysiscLcLMyClustercOallocatorlEDileptonAnalysiscLcLMyClustergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__embedana_DictLN_vectorlEDileptonAnalysiscLcLMyClustercOallocatorlEDileptonAnalysiscLcLMyClustergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<DileptonAnalysis::MyVTXHit>",117,G__get_linked_tagnum(&G__embedana_DictLN_vectorlEDileptonAnalysiscLcLMyVTXHitcOallocatorlEDileptonAnalysiscLcLMyVTXHitgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__embedana_DictLN_reverse_iteratorlEvectorlEDileptonAnalysiscLcLMyVTXHitcOallocatorlEDileptonAnalysiscLcLMyVTXHitgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__embedana_DictLN_vectorlEDileptonAnalysiscLcLMyVTXHitcOallocatorlEDileptonAnalysiscLcLMyVTXHitgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__embedana_DictLN_reverse_iteratorlEvectorlEDileptonAnalysiscLcLMyVTXHitcOallocatorlEDileptonAnalysiscLcLMyVTXHitgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__embedana_DictLN_vectorlEDileptonAnalysiscLcLMyVTXHitcOallocatorlEDileptonAnalysiscLcLMyVTXHitgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<DileptonAnalysis::MyGenTrack>",117,G__get_linked_tagnum(&G__embedana_DictLN_vectorlEDileptonAnalysiscLcLMyGenTrackcOallocatorlEDileptonAnalysiscLcLMyGenTrackgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__embedana_DictLN_reverse_iteratorlEvectorlEDileptonAnalysiscLcLMyGenTrackcOallocatorlEDileptonAnalysiscLcLMyGenTrackgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__embedana_DictLN_vectorlEDileptonAnalysiscLcLMyGenTrackcOallocatorlEDileptonAnalysiscLcLMyGenTrackgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__embedana_DictLN_reverse_iteratorlEvectorlEDileptonAnalysiscLcLMyGenTrackcOallocatorlEDileptonAnalysiscLcLMyGenTrackgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__embedana_DictLN_vectorlEDileptonAnalysiscLcLMyGenTrackcOallocatorlEDileptonAnalysiscLcLMyGenTrackgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<DileptonAnalysis::MyEvent>",117,G__get_linked_tagnum(&G__embedana_DictLN_vectorlEDileptonAnalysiscLcLMyEventcOallocatorlEDileptonAnalysiscLcLMyEventgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__embedana_DictLN_reverse_iteratorlEvectorlEDileptonAnalysiscLcLMyEventcOallocatorlEDileptonAnalysiscLcLMyEventgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__embedana_DictLN_vectorlEDileptonAnalysiscLcLMyEventcOallocatorlEDileptonAnalysiscLcLMyEventgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__embedana_DictLN_reverse_iteratorlEvectorlEDileptonAnalysiscLcLMyEventcOallocatorlEDileptonAnalysiscLcLMyEventgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__embedana_DictLN_vectorlEDileptonAnalysiscLcLMyEventcOallocatorlEDileptonAnalysiscLcLMyEventgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("deque<DileptonAnalysis::MyEvent>",117,G__get_linked_tagnum(&G__embedana_DictLN_dequelEDileptonAnalysiscLcLMyEventcOallocatorlEDileptonAnalysiscLcLMyEventgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<DileptonAnalysis::MyBDTrack>",117,G__get_linked_tagnum(&G__embedana_DictLN_vectorlEDileptonAnalysiscLcLMyBDTrackcOallocatorlEDileptonAnalysiscLcLMyBDTrackgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__embedana_DictLN_reverse_iteratorlEvectorlEDileptonAnalysiscLcLMyBDTrackcOallocatorlEDileptonAnalysiscLcLMyBDTrackgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__embedana_DictLN_vectorlEDileptonAnalysiscLcLMyBDTrackcOallocatorlEDileptonAnalysiscLcLMyBDTrackgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__embedana_DictLN_reverse_iteratorlEvectorlEDileptonAnalysiscLcLMyBDTrackcOallocatorlEDileptonAnalysiscLcLMyBDTrackgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__embedana_DictLN_vectorlEDileptonAnalysiscLcLMyBDTrackcOallocatorlEDileptonAnalysiscLcLMyBDTrackgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* DileptonAnalysis */
static void G__setup_memvarDileptonAnalysis(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__embedana_DictLN_DileptonAnalysis));
   {
   }
   G__tag_memvar_reset();
}


   /* embedana */
static void G__setup_memvarembedana(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__embedana_DictLN_embedana));
   { embedana *p; p=(embedana*)0x1000; if (p) { }
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"EventNumber=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"InPartNumber=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"InIDread=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__embedana_DictLN_string),-1,-1,4,"m_outFileName=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"fill_TTree=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"remove_cluster_hits=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__embedana_DictLN_string),-1,-1,4,"local_filepath=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__embedana_DictLN_string),-1,-1,4,"local_oscarpath=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__embedana_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"vertexes=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__embedana_DictLN_InData),-1,-1,4,"InData_read[100000]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"dcmap_runs[9][500]=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"dcmap_xx1[9][2][2][20]=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"dcmap_yy1[9][2][2][20]=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"dcmap_xx2[9][2][2][20]=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"dcmap_yy2[9][2][2][20]=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"dcmap_xx3[9][2][2][20]=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"dcmap_yy3[9][2][2][20]=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"dcmap_xx4[9][2][2][20]=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"dcmap_yy4[9][2][2][20]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"TRIGGERBIT=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"BBC_VERTEX_CUT=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"QUALITY[3]=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"Z_GLOBAL=",0,"<|cut value|");
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"DC_DEADMAP=",0,"0--w/o dc dead map, 1--w/ dc dead map");
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"E_PT=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"MAX_PT=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"N0=",0,">cut value");
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"DISP=",0,"<cut value");
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"CHI2_NPE0=",0,"< cut value");
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"EOVERP=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"DEP[2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"PROB=",0,">cut value");
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"TEMC=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"EMCDPHI=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"EMCDZ=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"EMCSDPHI=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"EMCSDZ=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"RICH_GHOST=",0,"RICH ghost cut");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__embedana_DictLN_DileptonAnalysiscLcLMyEventContainer),-1,-1,4,"event_container=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarembedana_Dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncDileptonAnalysis(void) {
   /* DileptonAnalysis */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__embedana_DictLN_DileptonAnalysis));
   G__tag_memfunc_reset();
}

static void G__setup_memfuncembedana(void) {
   /* embedana */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__embedana_DictLN_embedana));
   G__memfunc_setup("embedana",813,G__embedana_Dict_933_0_1, 105, G__get_linked_tagnum(&G__embedana_DictLN_embedana), -1, 0, 4, 1, 1, 0, 
"u 'string' - 0 '\"embedana.root\"' filename u 'string' - 0 '\"/gpfs/mnt/gpfs02/phenix/plhf/plhf1/mitran/Simul/Dileptons/real/work/output/vertexes.txt\"' filepath "
"u 'string' - 0 '\"/phenix/plhf/mitran/Simul/Dileptons/output_single/single/00002.oscar.particles.dat\"' oscarpath i - - 10 '1' InID", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Init",404,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "U 'PHCompositeNode' - 0 - topNode", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("process_event",1408,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "U 'PHCompositeNode' - 0 - topNode", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("End",279,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "U 'PHCompositeNode' - 0 - topNode", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ResetEvent",1029,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "U 'PHCompositeNode' - 0 - topNode", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Reset",515,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "U 'PHCompositeNode' - 0 - topNode", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("InitRun",713,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "U 'PHCompositeNode' - 0 - topNode", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Print",525,G__embedana_Dict_933_0_8, 121, -1, -1, 0, 1, 1, 1, 8, "C - - 10 - what", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("calcDCA_BCbyCircleProjection",2697,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 14, 1, 4, 0, 
"f - - 0 - pt f - - 0 - phi "
"f - - 0 - the i - - 0 - charge "
"f - - 0 - hx f - - 0 - hy "
"f - - 0 - hz f - - 0 - vx "
"f - - 0 - vy f - - 0 - fieldPolarity "
"F - - 0 - dx F - - 0 - dy "
"F - - 0 - dz F - - 0 - d2dca_bc", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("InitParams",1016,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("get_board",935,(G__InterfaceMethod) NULL, 102, -1, -1, 0, 1, 1, 4, 0, "f - - 0 - phi_dc", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("init_rungroup",1429,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("get_rungroup",1313,(G__InterfaceMethod) NULL, 105, -1, -1, 0, 1, 1, 4, 0, "i - - 0 - run_num", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("init_dead_area",1433,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("left_bound",1058,(G__InterfaceMethod) NULL, 103, -1, -1, 0, 6, 1, 4, 0, 
"f - - 0 - x f - - 0 - y "
"f - - 0 - xx1 f - - 0 - yy1 "
"f - - 0 - xx2 f - - 0 - yy2", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("right_bound",1173,(G__InterfaceMethod) NULL, 103, -1, -1, 0, 6, 1, 4, 0, 
"f - - 0 - x f - - 0 - y "
"f - - 0 - xx1 f - - 0 - yy1 "
"f - - 0 - xx2 f - - 0 - yy2", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("dead_region",1137,(G__InterfaceMethod) NULL, 103, -1, -1, 0, 10, 1, 4, 0, 
"f - - 0 - x f - - 0 - y "
"f - - 0 - xx1 f - - 0 - yy1 "
"f - - 0 - xx2 f - - 0 - yy2 "
"f - - 0 - xx3 f - - 0 - yy3 "
"f - - 0 - xx4 f - - 0 - yy4", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("IsCentralSupportCut",1966,(G__InterfaceMethod) NULL, 103, -1, -1, 0, 2, 1, 4, 0, 
"f - - 10 - theta0 f - - 10 - bbcVertex", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("applySingleTrackCut",1961,(G__InterfaceMethod) NULL, 105, -1, -1, 0, 5, 1, 4, 0, 
"U 'PHCentralTrack' - 10 - d_trk i - - 10 - itrk "
"f - - 10 - vertex f - - 10 - centrality "
"i - - 10 - run_number", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ReadOrigPartMoms",1600,(G__InterfaceMethod) NULL, 105, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("embedana", 813, G__embedana_Dict_933_0_21, (int) ('i'), G__get_linked_tagnum(&G__embedana_DictLN_embedana), -1, 0, 1, 1, 1, 0, "u 'embedana' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~embedana", 939, G__embedana_Dict_933_0_22, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__embedana_Dict_933_0_23, (int) ('u'), G__get_linked_tagnum(&G__embedana_DictLN_embedana), -1, 1, 1, 1, 1, 0, "u 'embedana' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncembedana_Dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {
}

static void G__cpp_setup_global7() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalembedana_Dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
  G__cpp_setup_global7();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {
}

static void G__cpp_setup_func26() {
}

static void G__cpp_setup_func27() {
}

static void G__cpp_setup_func28() {
}

static void G__cpp_setup_func29() {
}

static void G__cpp_setup_func30() {
}

static void G__cpp_setup_func31() {
}

static void G__cpp_setup_func32() {
}

static void G__cpp_setup_func33() {
}

static void G__cpp_setup_func34() {
}

static void G__cpp_setup_func35() {
}

static void G__cpp_setup_func36() {
}

static void G__cpp_setup_func37() {
}

static void G__cpp_setup_func38() {
}

static void G__cpp_setup_func39() {
}

static void G__cpp_setup_func40() {
}

static void G__cpp_setup_func41() {
}

static void G__cpp_setup_func42() {
}

static void G__cpp_setup_func43() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcembedana_Dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
  G__cpp_setup_func26();
  G__cpp_setup_func27();
  G__cpp_setup_func28();
  G__cpp_setup_func29();
  G__cpp_setup_func30();
  G__cpp_setup_func31();
  G__cpp_setup_func32();
  G__cpp_setup_func33();
  G__cpp_setup_func34();
  G__cpp_setup_func35();
  G__cpp_setup_func36();
  G__cpp_setup_func37();
  G__cpp_setup_func38();
  G__cpp_setup_func39();
  G__cpp_setup_func40();
  G__cpp_setup_func41();
  G__cpp_setup_func42();
  G__cpp_setup_func43();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__embedana_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_Fun4AllBase = { "Fun4AllBase" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_PHCompositeNode = { "PHCompositeNode" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_SubsysReco = { "SubsysReco" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR = { "map<string,int,less<string>,allocator<pair<const string,int> > >" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_maplEstringcOfloatcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOfloatgRsPgRsPgR = { "map<string,float,less<string>,allocator<pair<const string,float> > >" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR = { "map<string,double,less<string>,allocator<pair<const string,double> > >" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_maplEstringcOTBranchmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTBranchmUgRsPgRsPgR = { "map<string,TBranch*,less<string>,allocator<pair<const string,TBranch*> > >" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_maplEconstsPstringcOTNamedmUcOlesslEconstsPstringgRcOallocatorlEpairlEconstsPstringcOTNamedmUgRsPgRsPgR = { "map<const string,TNamed*,less<const string>,allocator<pair<const string,TNamed*> > >" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_vectorlEstringcOallocatorlEstringgRsPgR = { "vector<string,allocator<string> >" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<string,allocator<string> >::iterator>" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_vectorlEpairlESubsysRecomUcOPHCompositeNodemUgRcOallocatorlEpairlESubsysRecomUcOPHCompositeNodemUgRsPgRsPgR = { "vector<pair<SubsysReco*,PHCompositeNode*>,allocator<pair<SubsysReco*,PHCompositeNode*> > >" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_reverse_iteratorlEvectorlEpairlESubsysRecomUcOPHCompositeNodemUgRcOallocatorlEpairlESubsysRecomUcOPHCompositeNodemUgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<SubsysReco*,PHCompositeNode*>,allocator<pair<SubsysReco*,PHCompositeNode*> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_vectorlEFun4AllOutputManagermUcOallocatorlEFun4AllOutputManagermUgRsPgR = { "vector<Fun4AllOutputManager*,allocator<Fun4AllOutputManager*> >" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_reverse_iteratorlEvectorlEFun4AllOutputManagermUcOallocatorlEFun4AllOutputManagermUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<Fun4AllOutputManager*,allocator<Fun4AllOutputManager*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_vectorlETDirectorymUcOallocatorlETDirectorymUgRsPgR = { "vector<TDirectory*,allocator<TDirectory*> >" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_reverse_iteratorlEvectorlETDirectorymUcOallocatorlETDirectorymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TDirectory*,allocator<TDirectory*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_vectorlEFun4AllHistoManagermUcOallocatorlEFun4AllHistoManagermUgRsPgR = { "vector<Fun4AllHistoManager*,allocator<Fun4AllHistoManager*> >" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_reverse_iteratorlEvectorlEFun4AllHistoManagermUcOallocatorlEFun4AllHistoManagermUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<Fun4AllHistoManager*,allocator<Fun4AllHistoManager*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_maplEstringcOPHCompositeNodemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOPHCompositeNodemUgRsPgRsPgR = { "map<string,PHCompositeNode*,less<string>,allocator<pair<const string,PHCompositeNode*> > >" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_vectorlEFun4AllSyncManagermUcOallocatorlEFun4AllSyncManagermUgRsPgR = { "vector<Fun4AllSyncManager*,allocator<Fun4AllSyncManager*> >" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_reverse_iteratorlEvectorlEFun4AllSyncManagermUcOallocatorlEFun4AllSyncManagermUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<Fun4AllSyncManager*,allocator<Fun4AllSyncManager*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR = { "map<string,string,less<string>,allocator<pair<const string,string> > >" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_PHCentralTrack = { "PHCentralTrack" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_setlEunsignedsPintcOlesslEunsignedsPintgRcOallocatorlEunsignedsPintgRsPgR = { "set<unsigned int,less<unsigned int>,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__embedana_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_DileptonAnalysis = { "DileptonAnalysis" , 110 , -1 };
G__linked_taginfo G__embedana_DictLN_maplEintcOfloatcOlesslEintgRcOallocatorlEpairlEconstsPintcOfloatgRsPgRsPgR = { "map<int,float,less<int>,allocator<pair<const int,float> > >" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_vectorlEDileptonAnalysiscLcLMyBDTHitcOallocatorlEDileptonAnalysiscLcLMyBDTHitgRsPgR = { "vector<DileptonAnalysis::MyBDTHit,allocator<DileptonAnalysis::MyBDTHit> >" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_reverse_iteratorlEvectorlEDileptonAnalysiscLcLMyBDTHitcOallocatorlEDileptonAnalysiscLcLMyBDTHitgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<DileptonAnalysis::MyBDTHit,allocator<DileptonAnalysis::MyBDTHit> >::iterator>" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_vectorlEDileptonAnalysiscLcLMyElectroncOallocatorlEDileptonAnalysiscLcLMyElectrongRsPgR = { "vector<DileptonAnalysis::MyElectron,allocator<DileptonAnalysis::MyElectron> >" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_reverse_iteratorlEvectorlEDileptonAnalysiscLcLMyElectroncOallocatorlEDileptonAnalysiscLcLMyElectrongRsPgRcLcLiteratorgR = { "reverse_iterator<vector<DileptonAnalysis::MyElectron,allocator<DileptonAnalysis::MyElectron> >::iterator>" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_vectorlEDileptonAnalysiscLcLMyClustercOallocatorlEDileptonAnalysiscLcLMyClustergRsPgR = { "vector<DileptonAnalysis::MyCluster,allocator<DileptonAnalysis::MyCluster> >" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_reverse_iteratorlEvectorlEDileptonAnalysiscLcLMyClustercOallocatorlEDileptonAnalysiscLcLMyClustergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<DileptonAnalysis::MyCluster,allocator<DileptonAnalysis::MyCluster> >::iterator>" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_vectorlEDileptonAnalysiscLcLMyVTXHitcOallocatorlEDileptonAnalysiscLcLMyVTXHitgRsPgR = { "vector<DileptonAnalysis::MyVTXHit,allocator<DileptonAnalysis::MyVTXHit> >" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_reverse_iteratorlEvectorlEDileptonAnalysiscLcLMyVTXHitcOallocatorlEDileptonAnalysiscLcLMyVTXHitgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<DileptonAnalysis::MyVTXHit,allocator<DileptonAnalysis::MyVTXHit> >::iterator>" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_vectorlEDileptonAnalysiscLcLMyGenTrackcOallocatorlEDileptonAnalysiscLcLMyGenTrackgRsPgR = { "vector<DileptonAnalysis::MyGenTrack,allocator<DileptonAnalysis::MyGenTrack> >" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_reverse_iteratorlEvectorlEDileptonAnalysiscLcLMyGenTrackcOallocatorlEDileptonAnalysiscLcLMyGenTrackgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<DileptonAnalysis::MyGenTrack,allocator<DileptonAnalysis::MyGenTrack> >::iterator>" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_DileptonAnalysiscLcLMyEventContainer = { "DileptonAnalysis::MyEventContainer" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_vectorlEDileptonAnalysiscLcLMyEventcOallocatorlEDileptonAnalysiscLcLMyEventgRsPgR = { "vector<DileptonAnalysis::MyEvent,allocator<DileptonAnalysis::MyEvent> >" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_reverse_iteratorlEvectorlEDileptonAnalysiscLcLMyEventcOallocatorlEDileptonAnalysiscLcLMyEventgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<DileptonAnalysis::MyEvent,allocator<DileptonAnalysis::MyEvent> >::iterator>" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_dequelEDileptonAnalysiscLcLMyEventcOallocatorlEDileptonAnalysiscLcLMyEventgRsPgR = { "deque<DileptonAnalysis::MyEvent,allocator<DileptonAnalysis::MyEvent> >" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_vectorlEDileptonAnalysiscLcLMyBDTrackcOallocatorlEDileptonAnalysiscLcLMyBDTrackgRsPgR = { "vector<DileptonAnalysis::MyBDTrack,allocator<DileptonAnalysis::MyBDTrack> >" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_reverse_iteratorlEvectorlEDileptonAnalysiscLcLMyBDTrackcOallocatorlEDileptonAnalysiscLcLMyBDTrackgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<DileptonAnalysis::MyBDTrack,allocator<DileptonAnalysis::MyBDTrack> >::iterator>" , 99 , -1 };
G__linked_taginfo G__embedana_DictLN_InData = { "InData" , 115 , -1 };
G__linked_taginfo G__embedana_DictLN_embedana = { "embedana" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableembedana_Dict() {
  G__embedana_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__embedana_DictLN_string.tagnum = -1 ;
  G__embedana_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__embedana_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__embedana_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__embedana_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__embedana_DictLN_Fun4AllBase.tagnum = -1 ;
  G__embedana_DictLN_PHCompositeNode.tagnum = -1 ;
  G__embedana_DictLN_SubsysReco.tagnum = -1 ;
  G__embedana_DictLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR.tagnum = -1 ;
  G__embedana_DictLN_maplEstringcOfloatcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOfloatgRsPgRsPgR.tagnum = -1 ;
  G__embedana_DictLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR.tagnum = -1 ;
  G__embedana_DictLN_maplEstringcOTBranchmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTBranchmUgRsPgRsPgR.tagnum = -1 ;
  G__embedana_DictLN_maplEconstsPstringcOTNamedmUcOlesslEconstsPstringgRcOallocatorlEpairlEconstsPstringcOTNamedmUgRsPgRsPgR.tagnum = -1 ;
  G__embedana_DictLN_vectorlEstringcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G__embedana_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__embedana_DictLN_vectorlEpairlESubsysRecomUcOPHCompositeNodemUgRcOallocatorlEpairlESubsysRecomUcOPHCompositeNodemUgRsPgRsPgR.tagnum = -1 ;
  G__embedana_DictLN_reverse_iteratorlEvectorlEpairlESubsysRecomUcOPHCompositeNodemUgRcOallocatorlEpairlESubsysRecomUcOPHCompositeNodemUgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__embedana_DictLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__embedana_DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__embedana_DictLN_vectorlEFun4AllOutputManagermUcOallocatorlEFun4AllOutputManagermUgRsPgR.tagnum = -1 ;
  G__embedana_DictLN_reverse_iteratorlEvectorlEFun4AllOutputManagermUcOallocatorlEFun4AllOutputManagermUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__embedana_DictLN_vectorlETDirectorymUcOallocatorlETDirectorymUgRsPgR.tagnum = -1 ;
  G__embedana_DictLN_reverse_iteratorlEvectorlETDirectorymUcOallocatorlETDirectorymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__embedana_DictLN_vectorlEFun4AllHistoManagermUcOallocatorlEFun4AllHistoManagermUgRsPgR.tagnum = -1 ;
  G__embedana_DictLN_reverse_iteratorlEvectorlEFun4AllHistoManagermUcOallocatorlEFun4AllHistoManagermUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__embedana_DictLN_maplEstringcOPHCompositeNodemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOPHCompositeNodemUgRsPgRsPgR.tagnum = -1 ;
  G__embedana_DictLN_vectorlEFun4AllSyncManagermUcOallocatorlEFun4AllSyncManagermUgRsPgR.tagnum = -1 ;
  G__embedana_DictLN_reverse_iteratorlEvectorlEFun4AllSyncManagermUcOallocatorlEFun4AllSyncManagermUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__embedana_DictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR.tagnum = -1 ;
  G__embedana_DictLN_PHCentralTrack.tagnum = -1 ;
  G__embedana_DictLN_setlEunsignedsPintcOlesslEunsignedsPintgRcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__embedana_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__embedana_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__embedana_DictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__embedana_DictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__embedana_DictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__embedana_DictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__embedana_DictLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__embedana_DictLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__embedana_DictLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__embedana_DictLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__embedana_DictLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__embedana_DictLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__embedana_DictLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__embedana_DictLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__embedana_DictLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__embedana_DictLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__embedana_DictLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__embedana_DictLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__embedana_DictLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__embedana_DictLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__embedana_DictLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__embedana_DictLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__embedana_DictLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__embedana_DictLN_DileptonAnalysis.tagnum = -1 ;
  G__embedana_DictLN_maplEintcOfloatcOlesslEintgRcOallocatorlEpairlEconstsPintcOfloatgRsPgRsPgR.tagnum = -1 ;
  G__embedana_DictLN_vectorlEDileptonAnalysiscLcLMyBDTHitcOallocatorlEDileptonAnalysiscLcLMyBDTHitgRsPgR.tagnum = -1 ;
  G__embedana_DictLN_reverse_iteratorlEvectorlEDileptonAnalysiscLcLMyBDTHitcOallocatorlEDileptonAnalysiscLcLMyBDTHitgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__embedana_DictLN_vectorlEDileptonAnalysiscLcLMyElectroncOallocatorlEDileptonAnalysiscLcLMyElectrongRsPgR.tagnum = -1 ;
  G__embedana_DictLN_reverse_iteratorlEvectorlEDileptonAnalysiscLcLMyElectroncOallocatorlEDileptonAnalysiscLcLMyElectrongRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__embedana_DictLN_vectorlEDileptonAnalysiscLcLMyClustercOallocatorlEDileptonAnalysiscLcLMyClustergRsPgR.tagnum = -1 ;
  G__embedana_DictLN_reverse_iteratorlEvectorlEDileptonAnalysiscLcLMyClustercOallocatorlEDileptonAnalysiscLcLMyClustergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__embedana_DictLN_vectorlEDileptonAnalysiscLcLMyVTXHitcOallocatorlEDileptonAnalysiscLcLMyVTXHitgRsPgR.tagnum = -1 ;
  G__embedana_DictLN_reverse_iteratorlEvectorlEDileptonAnalysiscLcLMyVTXHitcOallocatorlEDileptonAnalysiscLcLMyVTXHitgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__embedana_DictLN_vectorlEDileptonAnalysiscLcLMyGenTrackcOallocatorlEDileptonAnalysiscLcLMyGenTrackgRsPgR.tagnum = -1 ;
  G__embedana_DictLN_reverse_iteratorlEvectorlEDileptonAnalysiscLcLMyGenTrackcOallocatorlEDileptonAnalysiscLcLMyGenTrackgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__embedana_DictLN_DileptonAnalysiscLcLMyEventContainer.tagnum = -1 ;
  G__embedana_DictLN_vectorlEDileptonAnalysiscLcLMyEventcOallocatorlEDileptonAnalysiscLcLMyEventgRsPgR.tagnum = -1 ;
  G__embedana_DictLN_reverse_iteratorlEvectorlEDileptonAnalysiscLcLMyEventcOallocatorlEDileptonAnalysiscLcLMyEventgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__embedana_DictLN_dequelEDileptonAnalysiscLcLMyEventcOallocatorlEDileptonAnalysiscLcLMyEventgRsPgR.tagnum = -1 ;
  G__embedana_DictLN_vectorlEDileptonAnalysiscLcLMyBDTrackcOallocatorlEDileptonAnalysiscLcLMyBDTrackgRsPgR.tagnum = -1 ;
  G__embedana_DictLN_reverse_iteratorlEvectorlEDileptonAnalysiscLcLMyBDTrackcOallocatorlEDileptonAnalysiscLcLMyBDTrackgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__embedana_DictLN_InData.tagnum = -1 ;
  G__embedana_DictLN_embedana.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableembedana_Dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_string);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_Fun4AllBase);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_PHCompositeNode);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_SubsysReco);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_maplEstringcOfloatcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOfloatgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_maplEstringcOTBranchmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTBranchmUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_maplEconstsPstringcOTNamedmUcOlesslEconstsPstringgRcOallocatorlEpairlEconstsPstringcOTNamedmUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_vectorlEstringcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_vectorlEpairlESubsysRecomUcOPHCompositeNodemUgRcOallocatorlEpairlESubsysRecomUcOPHCompositeNodemUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_reverse_iteratorlEvectorlEpairlESubsysRecomUcOPHCompositeNodemUgRcOallocatorlEpairlESubsysRecomUcOPHCompositeNodemUgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_vectorlEFun4AllOutputManagermUcOallocatorlEFun4AllOutputManagermUgRsPgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_reverse_iteratorlEvectorlEFun4AllOutputManagermUcOallocatorlEFun4AllOutputManagermUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_vectorlETDirectorymUcOallocatorlETDirectorymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_reverse_iteratorlEvectorlETDirectorymUcOallocatorlETDirectorymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_vectorlEFun4AllHistoManagermUcOallocatorlEFun4AllHistoManagermUgRsPgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_reverse_iteratorlEvectorlEFun4AllHistoManagermUcOallocatorlEFun4AllHistoManagermUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_maplEstringcOPHCompositeNodemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOPHCompositeNodemUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_vectorlEFun4AllSyncManagermUcOallocatorlEFun4AllSyncManagermUgRsPgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_reverse_iteratorlEvectorlEFun4AllSyncManagermUcOallocatorlEFun4AllSyncManagermUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_PHCentralTrack);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_setlEunsignedsPintcOlesslEunsignedsPintgRcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_TMatrixTSparseDiaglEfloatgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__embedana_DictLN_DileptonAnalysis),0,-1,0,(char*)NULL,G__setup_memvarDileptonAnalysis,G__setup_memfuncDileptonAnalysis);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_maplEintcOfloatcOlesslEintgRcOallocatorlEpairlEconstsPintcOfloatgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_vectorlEDileptonAnalysiscLcLMyBDTHitcOallocatorlEDileptonAnalysiscLcLMyBDTHitgRsPgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_reverse_iteratorlEvectorlEDileptonAnalysiscLcLMyBDTHitcOallocatorlEDileptonAnalysiscLcLMyBDTHitgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_vectorlEDileptonAnalysiscLcLMyElectroncOallocatorlEDileptonAnalysiscLcLMyElectrongRsPgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_reverse_iteratorlEvectorlEDileptonAnalysiscLcLMyElectroncOallocatorlEDileptonAnalysiscLcLMyElectrongRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_vectorlEDileptonAnalysiscLcLMyClustercOallocatorlEDileptonAnalysiscLcLMyClustergRsPgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_reverse_iteratorlEvectorlEDileptonAnalysiscLcLMyClustercOallocatorlEDileptonAnalysiscLcLMyClustergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_vectorlEDileptonAnalysiscLcLMyVTXHitcOallocatorlEDileptonAnalysiscLcLMyVTXHitgRsPgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_reverse_iteratorlEvectorlEDileptonAnalysiscLcLMyVTXHitcOallocatorlEDileptonAnalysiscLcLMyVTXHitgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_vectorlEDileptonAnalysiscLcLMyGenTrackcOallocatorlEDileptonAnalysiscLcLMyGenTrackgRsPgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_reverse_iteratorlEvectorlEDileptonAnalysiscLcLMyGenTrackcOallocatorlEDileptonAnalysiscLcLMyGenTrackgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_DileptonAnalysiscLcLMyEventContainer);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_vectorlEDileptonAnalysiscLcLMyEventcOallocatorlEDileptonAnalysiscLcLMyEventgRsPgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_reverse_iteratorlEvectorlEDileptonAnalysiscLcLMyEventcOallocatorlEDileptonAnalysiscLcLMyEventgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_dequelEDileptonAnalysiscLcLMyEventcOallocatorlEDileptonAnalysiscLcLMyEventgRsPgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_vectorlEDileptonAnalysiscLcLMyBDTrackcOallocatorlEDileptonAnalysiscLcLMyBDTrackgRsPgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_reverse_iteratorlEvectorlEDileptonAnalysiscLcLMyBDTrackcOallocatorlEDileptonAnalysiscLcLMyBDTrackgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__embedana_DictLN_InData);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__embedana_DictLN_embedana),sizeof(embedana),-1,263424,(char*)NULL,G__setup_memvarembedana,G__setup_memfuncembedana);
}
extern "C" void G__cpp_setupembedana_Dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupembedana_Dict()");
  G__set_cpp_environmentembedana_Dict();
  G__cpp_setup_tagtableembedana_Dict();

  G__cpp_setup_inheritanceembedana_Dict();

  G__cpp_setup_typetableembedana_Dict();

  G__cpp_setup_memvarembedana_Dict();

  G__cpp_setup_memfuncembedana_Dict();
  G__cpp_setup_globalembedana_Dict();
  G__cpp_setup_funcembedana_Dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncembedana_Dict();
  return;
}
class G__cpp_setup_initembedana_Dict {
  public:
    G__cpp_setup_initembedana_Dict() { G__add_setup_func("embedana_Dict",(G__incsetup)(&G__cpp_setupembedana_Dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initembedana_Dict() { G__remove_setup_func("embedana_Dict"); }
};
G__cpp_setup_initembedana_Dict G__cpp_setup_initializerembedana_Dict;

