//
// File generated by rootcint at Thu Mar 12 15:28:31 2026

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME Reconstruction_Dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "Reconstruction_Dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace DileptonAnalysis {
   namespace ROOTDict {
      inline ::ROOT::TGenericClassInfo *GenerateInitInstance();
      static void DileptonAnalysis_Dictionary();

      // Function generating the singleton type initializer
      inline ::ROOT::TGenericClassInfo *GenerateInitInstance()
      {
         static ::ROOT::TGenericClassInfo 
            instance("DileptonAnalysis", 0 /*version*/, "./Reconstruction.h", 9,
                     ::ROOT::DefineBehavior((void*)0,(void*)0),
                     &DileptonAnalysis_Dictionary, 0);
         return &instance;
      }
      // Insure that the inline function is _not_ optimized away by the compiler
      ::ROOT::TGenericClassInfo *(*_R__UNIQUE_(InitFunctionKeeper))() = &GenerateInitInstance;  
      // Static variable to force the class initialization
      static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstance(); R__UseDummy(_R__UNIQUE_(Init));

      // Dictionary for non-ClassDef classes
      static void DileptonAnalysis_Dictionary() {
         GenerateInitInstance()->GetClass();
      }

   }
}

namespace ROOTDict {
   void DileptonAnalysiscLcLReconstruction_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void DileptonAnalysiscLcLReconstruction_Dictionary();
   static void delete_DileptonAnalysiscLcLReconstruction(void *p);
   static void deleteArray_DileptonAnalysiscLcLReconstruction(void *p);
   static void destruct_DileptonAnalysiscLcLReconstruction(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::DileptonAnalysis::Reconstruction*)
   {
      ::DileptonAnalysis::Reconstruction *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::DileptonAnalysis::Reconstruction),0);
      static ::ROOT::TGenericClassInfo 
         instance("DileptonAnalysis::Reconstruction", "./Reconstruction.h", 15,
                  typeid(::DileptonAnalysis::Reconstruction), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &DileptonAnalysiscLcLReconstruction_Dictionary, isa_proxy, 1,
                  sizeof(::DileptonAnalysis::Reconstruction) );
      instance.SetDelete(&delete_DileptonAnalysiscLcLReconstruction);
      instance.SetDeleteArray(&deleteArray_DileptonAnalysiscLcLReconstruction);
      instance.SetDestructor(&destruct_DileptonAnalysiscLcLReconstruction);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::DileptonAnalysis::Reconstruction*)
   {
      return GenerateInitInstanceLocal((::DileptonAnalysis::Reconstruction*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::DileptonAnalysis::Reconstruction*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void DileptonAnalysiscLcLReconstruction_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::DileptonAnalysis::Reconstruction*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrapper around operator delete
   static void delete_DileptonAnalysiscLcLReconstruction(void *p) {
      delete ((::DileptonAnalysis::Reconstruction*)p);
   }
   static void deleteArray_DileptonAnalysiscLcLReconstruction(void *p) {
      delete [] ((::DileptonAnalysis::Reconstruction*)p);
   }
   static void destruct_DileptonAnalysiscLcLReconstruction(void *p) {
      typedef ::DileptonAnalysis::Reconstruction current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::DileptonAnalysis::Reconstruction

/********************************************************
* Reconstruction_Dict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableReconstruction_Dict();

extern "C" void G__set_cpp_environmentReconstruction_Dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("Reconstruction.h");
  G__cpp_reset_tagtableReconstruction_Dict();
}
#include <new>
extern "C" int G__cpp_dllrevReconstruction_Dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* DileptonAnalysis */

/* DileptonAnalysis::Reconstruction */
static int G__Reconstruction_Dict_224_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   DileptonAnalysis::Reconstruction* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new DileptonAnalysis::Reconstruction((const char*) G__int(libp->para[0]));
   } else {
     p = new((void*) gvp) DileptonAnalysis::Reconstruction((const char*) G__int(libp->para[0]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__Reconstruction_DictLN_DileptonAnalysiscLcLReconstruction));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Reconstruction_Dict_224_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DileptonAnalysis::Reconstruction*) G__getstructoffset())->findIntersection((DileptonAnalysis::MyTrack*) G__int(libp->para[0]), (DileptonAnalysis::MyTrack*) G__int(libp->para[1])
, (DileptonAnalysis::MyPair*) G__int(libp->para[2]), (float) G__double(libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Reconstruction_Dict_224_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TVector3* pobj;
         TVector3 xobj = ((DileptonAnalysis::Reconstruction*) G__getstructoffset())->findMomentum((DileptonAnalysis::MyTrack*) G__int(libp->para[0]), (float) G__double(libp->para[1])
, (float) G__double(libp->para[2]), (float) G__double(libp->para[3])
, (float) G__double(libp->para[4]));
         pobj = new TVector3(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef DileptonAnalysis::Reconstruction G__TDileptonAnalysiscLcLReconstruction;
static int G__Reconstruction_Dict_224_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (DileptonAnalysis::Reconstruction*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((DileptonAnalysis::Reconstruction*) (soff+(sizeof(DileptonAnalysis::Reconstruction)*i)))->~G__TDileptonAnalysiscLcLReconstruction();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (DileptonAnalysis::Reconstruction*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((DileptonAnalysis::Reconstruction*) (soff))->~G__TDileptonAnalysiscLcLReconstruction();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__Reconstruction_Dict_224_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   DileptonAnalysis::Reconstruction* dest = (DileptonAnalysis::Reconstruction*) G__getstructoffset();
   *dest = *(DileptonAnalysis::Reconstruction*) libp->para[0].ref;
   const DileptonAnalysis::Reconstruction& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* DileptonAnalysis */

/* DileptonAnalysis::Reconstruction */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncReconstruction_Dict {
 public:
  G__Sizep2memfuncReconstruction_Dict(): p(&G__Sizep2memfuncReconstruction_Dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncReconstruction_Dict::*p)();
};

size_t G__get_sizep2memfuncReconstruction_Dict()
{
  G__Sizep2memfuncReconstruction_Dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceReconstruction_Dict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableReconstruction_Dict() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__Reconstruction_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__Reconstruction_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Reconstruction_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__Reconstruction_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Reconstruction_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__Reconstruction_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__Reconstruction_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Reconstruction_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__Reconstruction_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Reconstruction_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__Reconstruction_DictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__Reconstruction_DictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__Reconstruction_DictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__Reconstruction_DictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__Reconstruction_DictLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__Reconstruction_DictLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__Reconstruction_DictLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__Reconstruction_DictLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__Reconstruction_DictLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__Reconstruction_DictLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__Reconstruction_DictLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__Reconstruction_DictLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__Reconstruction_DictLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__Reconstruction_DictLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__Reconstruction_DictLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__Reconstruction_DictLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__Reconstruction_DictLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__Reconstruction_DictLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__Reconstruction_DictLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__Reconstruction_DictLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__Reconstruction_DictLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* DileptonAnalysis */
static void G__setup_memvarDileptonAnalysis(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__Reconstruction_DictLN_DileptonAnalysis));
   {
   }
   G__tag_memvar_reset();
}


   /* DileptonAnalysis::Reconstruction */
static void G__setup_memvarDileptonAnalysiscLcLReconstruction(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__Reconstruction_DictLN_DileptonAnalysiscLcLReconstruction));
   { DileptonAnalysis::Reconstruction *p; p=(DileptonAnalysis::Reconstruction*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__Reconstruction_DictLN_DileptonAnalysiscLcLReconstructioncLcLimpl),-1,-1,4,"pimpl=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarReconstruction_Dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncDileptonAnalysis(void) {
   /* DileptonAnalysis */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__Reconstruction_DictLN_DileptonAnalysis));
   G__tag_memfunc_reset();
}

static void G__setup_memfuncDileptonAnalysiscLcLReconstruction(void) {
   /* DileptonAnalysis::Reconstruction */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__Reconstruction_DictLN_DileptonAnalysiscLcLReconstruction));
   G__memfunc_setup("Reconstruction",1506,G__Reconstruction_Dict_224_0_1, 105, G__get_linked_tagnum(&G__Reconstruction_DictLN_DileptonAnalysiscLcLReconstruction), -1, 0, 1, 1, 1, 0, "C - - 10 - lookup_file_name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("findIntersection",1688,G__Reconstruction_Dict_224_0_2, 121, -1, -1, 0, 4, 1, 1, 0, 
"U 'DileptonAnalysis::MyTrack' - 10 - trk1 U 'DileptonAnalysis::MyTrack' - 10 - trk2 "
"U 'DileptonAnalysis::MyPair' - 0 - pair f - - 0 - zvertex", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("findMomentum",1267,G__Reconstruction_Dict_224_0_3, 117, G__get_linked_tagnum(&G__Reconstruction_DictLN_TVector3), -1, 0, 5, 1, 1, 0, 
"U 'DileptonAnalysis::MyTrack' - 0 - trk f - - 0 - r_conv "
"f - - 0 - phi_conv f - - 0 - theta_conv "
"f - - 0 - zvertex", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Reconstruction",1506,(G__InterfaceMethod) NULL, 105, G__get_linked_tagnum(&G__Reconstruction_DictLN_DileptonAnalysiscLcLReconstruction), -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Reconstruction",1506,(G__InterfaceMethod) NULL, 105, G__get_linked_tagnum(&G__Reconstruction_DictLN_DileptonAnalysiscLcLReconstruction), -1, 0, 1, 1, 4, 0, "u 'DileptonAnalysis::Reconstruction' - 41 - -", (char*)NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~Reconstruction", 1632, G__Reconstruction_Dict_224_0_6, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__Reconstruction_Dict_224_0_7, (int) ('u'), G__get_linked_tagnum(&G__Reconstruction_DictLN_DileptonAnalysiscLcLReconstruction), -1, 1, 1, 1, 1, 0, "u 'DileptonAnalysis::Reconstruction' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncReconstruction_Dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalReconstruction_Dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcReconstruction_Dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__Reconstruction_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__Reconstruction_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__Reconstruction_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__Reconstruction_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__Reconstruction_DictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__Reconstruction_DictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__Reconstruction_DictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__Reconstruction_DictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__Reconstruction_DictLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__Reconstruction_DictLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__Reconstruction_DictLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__Reconstruction_DictLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__Reconstruction_DictLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__Reconstruction_DictLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__Reconstruction_DictLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__Reconstruction_DictLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__Reconstruction_DictLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__Reconstruction_DictLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__Reconstruction_DictLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__Reconstruction_DictLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__Reconstruction_DictLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__Reconstruction_DictLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__Reconstruction_DictLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__Reconstruction_DictLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__Reconstruction_DictLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__Reconstruction_DictLN_TVector3 = { "TVector3" , 99 , -1 };
G__linked_taginfo G__Reconstruction_DictLN_DileptonAnalysis = { "DileptonAnalysis" , 110 , -1 };
G__linked_taginfo G__Reconstruction_DictLN_DileptonAnalysiscLcLMyTrack = { "DileptonAnalysis::MyTrack" , 99 , -1 };
G__linked_taginfo G__Reconstruction_DictLN_DileptonAnalysiscLcLMyPair = { "DileptonAnalysis::MyPair" , 99 , -1 };
G__linked_taginfo G__Reconstruction_DictLN_DileptonAnalysiscLcLReconstruction = { "DileptonAnalysis::Reconstruction" , 99 , -1 };
G__linked_taginfo G__Reconstruction_DictLN_DileptonAnalysiscLcLReconstructioncLcLimpl = { "DileptonAnalysis::Reconstruction::impl" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableReconstruction_Dict() {
  G__Reconstruction_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__Reconstruction_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__Reconstruction_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__Reconstruction_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__Reconstruction_DictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__Reconstruction_DictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__Reconstruction_DictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__Reconstruction_DictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__Reconstruction_DictLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__Reconstruction_DictLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__Reconstruction_DictLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__Reconstruction_DictLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__Reconstruction_DictLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__Reconstruction_DictLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__Reconstruction_DictLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__Reconstruction_DictLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__Reconstruction_DictLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__Reconstruction_DictLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__Reconstruction_DictLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__Reconstruction_DictLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__Reconstruction_DictLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__Reconstruction_DictLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__Reconstruction_DictLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__Reconstruction_DictLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__Reconstruction_DictLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__Reconstruction_DictLN_TVector3.tagnum = -1 ;
  G__Reconstruction_DictLN_DileptonAnalysis.tagnum = -1 ;
  G__Reconstruction_DictLN_DileptonAnalysiscLcLMyTrack.tagnum = -1 ;
  G__Reconstruction_DictLN_DileptonAnalysiscLcLMyPair.tagnum = -1 ;
  G__Reconstruction_DictLN_DileptonAnalysiscLcLReconstruction.tagnum = -1 ;
  G__Reconstruction_DictLN_DileptonAnalysiscLcLReconstructioncLcLimpl.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableReconstruction_Dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__Reconstruction_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__Reconstruction_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__Reconstruction_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__Reconstruction_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__Reconstruction_DictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__Reconstruction_DictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__Reconstruction_DictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Reconstruction_DictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__Reconstruction_DictLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Reconstruction_DictLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Reconstruction_DictLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Reconstruction_DictLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Reconstruction_DictLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Reconstruction_DictLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Reconstruction_DictLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Reconstruction_DictLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Reconstruction_DictLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Reconstruction_DictLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Reconstruction_DictLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Reconstruction_DictLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Reconstruction_DictLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__Reconstruction_DictLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Reconstruction_DictLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__Reconstruction_DictLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Reconstruction_DictLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__Reconstruction_DictLN_TVector3);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__Reconstruction_DictLN_DileptonAnalysis),0,-1,0,(char*)NULL,G__setup_memvarDileptonAnalysis,G__setup_memfuncDileptonAnalysis);
   G__get_linked_tagnum_fwd(&G__Reconstruction_DictLN_DileptonAnalysiscLcLMyTrack);
   G__get_linked_tagnum_fwd(&G__Reconstruction_DictLN_DileptonAnalysiscLcLMyPair);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__Reconstruction_DictLN_DileptonAnalysiscLcLReconstruction),sizeof(DileptonAnalysis::Reconstruction),-1,100096,(char*)NULL,G__setup_memvarDileptonAnalysiscLcLReconstruction,G__setup_memfuncDileptonAnalysiscLcLReconstruction);
   G__get_linked_tagnum_fwd(&G__Reconstruction_DictLN_DileptonAnalysiscLcLReconstructioncLcLimpl);
}
extern "C" void G__cpp_setupReconstruction_Dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupReconstruction_Dict()");
  G__set_cpp_environmentReconstruction_Dict();
  G__cpp_setup_tagtableReconstruction_Dict();

  G__cpp_setup_inheritanceReconstruction_Dict();

  G__cpp_setup_typetableReconstruction_Dict();

  G__cpp_setup_memvarReconstruction_Dict();

  G__cpp_setup_memfuncReconstruction_Dict();
  G__cpp_setup_globalReconstruction_Dict();
  G__cpp_setup_funcReconstruction_Dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncReconstruction_Dict();
  return;
}
class G__cpp_setup_initReconstruction_Dict {
  public:
    G__cpp_setup_initReconstruction_Dict() { G__add_setup_func("Reconstruction_Dict",(G__incsetup)(&G__cpp_setupReconstruction_Dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initReconstruction_Dict() { G__remove_setup_func("Reconstruction_Dict"); }
};
G__cpp_setup_initReconstruction_Dict G__cpp_setup_initializerReconstruction_Dict;

