/********************************************************************
* Reconstruction_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error Reconstruction_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableReconstruction_Dict();
extern void G__cpp_setup_inheritanceReconstruction_Dict();
extern void G__cpp_setup_typetableReconstruction_Dict();
extern void G__cpp_setup_memvarReconstruction_Dict();
extern void G__cpp_setup_globalReconstruction_Dict();
extern void G__cpp_setup_memfuncReconstruction_Dict();
extern void G__cpp_setup_funcReconstruction_Dict();
extern void G__set_cpp_environmentReconstruction_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Reconstruction.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__Reconstruction_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__Reconstruction_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Reconstruction_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__Reconstruction_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Reconstruction_DictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__Reconstruction_DictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__Reconstruction_DictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__Reconstruction_DictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__Reconstruction_DictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__Reconstruction_DictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__Reconstruction_DictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__Reconstruction_DictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__Reconstruction_DictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__Reconstruction_DictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__Reconstruction_DictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__Reconstruction_DictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__Reconstruction_DictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__Reconstruction_DictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__Reconstruction_DictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__Reconstruction_DictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__Reconstruction_DictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__Reconstruction_DictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__Reconstruction_DictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__Reconstruction_DictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__Reconstruction_DictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__Reconstruction_DictLN_TVector3;
extern G__linked_taginfo G__Reconstruction_DictLN_DileptonAnalysis;
extern G__linked_taginfo G__Reconstruction_DictLN_DileptonAnalysiscLcLMyTrack;
extern G__linked_taginfo G__Reconstruction_DictLN_DileptonAnalysiscLcLMyPair;
extern G__linked_taginfo G__Reconstruction_DictLN_DileptonAnalysiscLcLReconstruction;
extern G__linked_taginfo G__Reconstruction_DictLN_DileptonAnalysiscLcLReconstructioncLcLimpl;

/* STUB derived class for protected member access */
